# Function to compute shift totals for sedatives
- Erina Ghosh 2017/04/15

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
%matplotlib inline
import Sedative_daily_totals_etl as med_etl

## Reading med file

In [2]:
inp_med_df = pd.read_csv('Cohort_all_med_170415.csv', parse_dates=['starttime', 'endtime',
                                                                  'STARTTIME', 'ENDTIME',
                                                                  'intime'])
inp_med_df.shape

(171508, 33)

## Extracting neuromuscular blocker IV subjects

In [3]:
cis_pts = inp_med_df.loc[((inp_med_df['ITEMID'] == 221555) & 
                          (inp_med_df['ORDERCATEGORYNAME'] == '01-Drips')),'ICUSTAY_ID']
len(cis_pts)

3115

In [4]:
len(cis_pts.unique())

145

In [5]:
vec_pts = inp_med_df.loc[((inp_med_df['ITEMID'] == 222062) & 
                          (inp_med_df['ORDERCATEGORYNAME'] == '01-Drips')),'ICUSTAY_ID']
len(vec_pts)
len(vec_pts.unique())

3

In [6]:
nmb_pt_list = list(cis_pts.unique())
for i in range(len(vec_pts.unique())):
    nmb_pt_list.append(vec_pts.unique()[i])
len(nmb_pt_list)

148

In [7]:
nmb_pt_list[:5]

[250919.0, 239759.0, 281561.0, 216145.0, 262011.0]

In [8]:
nmb_pt_list[-5:]

[299571.0, 211489.0, 290588.0, 241177.0, 228873.0]

In [25]:
len(nmb_pt_list.unique)

AttributeError: 'list' object has no attribute 'unique'

### Remove all rows with above ICU Stays

In [9]:
inp_med_df['nmb_flag'] = 0
for i in nmb_pt_list:
    inp_med_df.loc[inp_med_df['ICUSTAY_ID'] == i, 'nmb_flag'] = 1

inp_med_df.groupby(['nmb_flag']).count()

,Unnamed: 0,hadm_id,starttime,endtime,age,dayHrs,nightHrs,intime,los,icustay_id,...,ORDERCATEGORYNAME,SECONDARYORDERCATEGORYNAME,ORDERCOMPONENTTYPEDESCRIPTION,ORDERCATEGORYDESCRIPTION,PATIENTWEIGHT,TOTALAMOUNT,TOTALAMOUNTUOM,STATUSDESCRIPTION,sed_flag,LABEL
nmb_flag,,,,,,,,,,,,,,,,,,,,,
0,136000,136000,136000,136000,136000,136000,136000,136000,136000,136000,...,136000,83994,136000,136000,136000,83994,83994,136000,136000,136000
1,35508,35508,35508,35508,35508,35508,35508,35508,35508,35508,...,35508,25592,35508,35508,35508,25592,25592,35508,35508,35508

In [10]:
inp_med_df = inp_med_df[inp_med_df['nmb_flag'] == 0]
inp_med_df.shape

(136000, 34)

In [11]:
del inp_med_df['Unnamed: 0']

Saving file

In [12]:
inp_med_df.to_csv('170417_Cohort_Medlist.csv')

## Grouping rows by med type

In [13]:
inp_med_df.groupby(['LABEL']).count()

,hadm_id,starttime,endtime,age,dayHrs,nightHrs,intime,los,icustay_id,ROW_ID,...,ORDERCATEGORYNAME,SECONDARYORDERCATEGORYNAME,ORDERCOMPONENTTYPEDESCRIPTION,ORDERCATEGORYDESCRIPTION,PATIENTWEIGHT,TOTALAMOUNT,TOTALAMOUNTUOM,STATUSDESCRIPTION,sed_flag,nmb_flag
LABEL,,,,,,,,,,,,,,,,,,,,,
Cisatracurium,5,5,5,5,5,5,5,5,5,5,...,5,0,5,5,5,0,0,5,5,5
Dexmedetomidine (Precedex),4447,4447,4447,4447,4447,4447,4447,4447,4447,4447,...,4447,4447,4447,4447,4447,4447,4447,4447,4447,4447
Diazepam (Valium),880,880,880,880,880,880,880,880,880,880,...,880,0,880,880,880,0,0,880,880,880
Fentanyl,25151,25151,25151,25151,25151,25151,25151,25151,25151,25151,...,25151,5218,25151,25151,25151,5218,5218,25151,25151,25151
Fentanyl (Concentrate),13199,13199,13199,13199,13199,13199,13199,13199,13199,13199,...,13199,13199,13199,13199,13199,13199,13199,13199,13199,13199
Hydromorphone (Dilaudid),6313,6313,6313,6313,6313,6313,6313,6313,6313,6313,...,6313,28,6313,6313,6313,28,28,6313,6313,6313
Lorazepam (Ativan),3725,3725,3725,3725,3725,3725,3725,3725,3725,3725,...,3725,62,3725,3725,3725,62,62,3725,3725,3725
Meperidine (Demerol),127,127,127,127,127,127,127,127,127,127,...,127,0,127,127,127,0,0,127,127,127
Methadone Hydrochloride,244,244,244,244,244,244,244,244,244,244,...,244,7,244,244,244,7,7,244,244,244
Midazolam (Versed),20175,20175,20175,20175,20175,20175,20175,20175,20175,20175,...,20175,11428,20175,20175,20175,11428,11428,20175,20175,20175
Morphine Sulfate,6976,6976,6976,6976,6976,6976,6976,6976,6976,6976,...,6976,406,6976,6976,6976,406,406,6976,6976,6976
Propofol,54652,54652,54652,54652,54652,54652,54652,54652,54652,54652,...,54652,49199,54652,54652,54652,49199,49199,54652,54652,54652
Vecuronium,106,106,106,106,106,106,106,106,106,106,...,106,0,106,106,106,0,0,106,106,106

### Checking neuromuscular blockers

In [14]:
inp_med_df.loc[inp_med_df['LABEL'] == 'Cisatracurium']['ORDERCATEGORYNAME']

28490     05-Med Bolus
44374     05-Med Bolus
54319     05-Med Bolus
162258    05-Med Bolus
169268    05-Med Bolus
Name: ORDERCATEGORYNAME, dtype: object

In [14]:
inp_med_df[['ICUSTAY_ID','STARTTIME', 'ENDTIME', 'intime', 'starttime', 'endtime']].head()

,ICUSTAY_ID,STARTTIME,ENDTIME,intime,starttime,endtime
0,263099.0,2184-10-06 05:00:00,2184-10-06 05:01:00,2184-10-04 09:03:19,2184-10-04 12:00:00,2184-10-08 16:00:00
1,263099.0,2184-10-04 17:15:00,2184-10-04 17:16:00,2184-10-04 09:03:19,2184-10-04 12:00:00,2184-10-08 16:00:00
2,263099.0,2184-10-04 13:50:00,2184-10-04 13:51:00,2184-10-04 09:03:19,2184-10-04 12:00:00,2184-10-08 16:00:00
3,263099.0,2184-10-04 22:30:00,2184-10-04 22:31:00,2184-10-04 09:03:19,2184-10-04 12:00:00,2184-10-08 16:00:00
4,263099.0,2184-10-04 18:45:00,2184-10-04 18:46:00,2184-10-04 09:03:19,2184-10-04 12:00:00,2184-10-08 16:00:00

### Checking unique med units

In [15]:
inp_med_df.groupby(['RATEUOM']).count()

,hadm_id,starttime,endtime,age,dayHrs,nightHrs,intime,los,icustay_id,ROW_ID,...,SECONDARYORDERCATEGORYNAME,ORDERCOMPONENTTYPEDESCRIPTION,ORDERCATEGORYDESCRIPTION,PATIENTWEIGHT,TOTALAMOUNT,TOTALAMOUNTUOM,STATUSDESCRIPTION,sed_flag,LABEL,nmb_flag
RATEUOM,,,,,,,,,,,,,,,,,,,,,
mcg/hour,18417,18417,18417,18417,18417,18417,18417,18417,18417,18417,...,18417,18417,18417,18417,18417,18417,18417,18417,18417,18417
mcg/kg/hour,4447,4447,4447,4447,4447,4447,4447,4447,4447,4447,...,4447,4447,4447,4447,4447,4447,4447,4447,4447,4447
mcg/kg/min,49199,49199,49199,49199,49199,49199,49199,49199,49199,49199,...,49199,49199,49199,49199,49199,49199,49199,49199,49199,49199
mg/hour,11931,11931,11931,11931,11931,11931,11931,11931,11931,11931,...,11931,11931,11931,11931,11931,11931,11931,11931,11931,11931

In [16]:
inp_med_df.groupby(['TOTALAMOUNTUOM']).count()

,hadm_id,starttime,endtime,age,dayHrs,nightHrs,intime,los,icustay_id,ROW_ID,...,ORDERCATEGORYNAME,SECONDARYORDERCATEGORYNAME,ORDERCOMPONENTTYPEDESCRIPTION,ORDERCATEGORYDESCRIPTION,PATIENTWEIGHT,TOTALAMOUNT,STATUSDESCRIPTION,sed_flag,LABEL,nmb_flag
TOTALAMOUNTUOM,,,,,,,,,,,,,,,,,,,,,
ml,83994,83994,83994,83994,83994,83994,83994,83994,83994,83994,...,83994,83994,83994,83994,83994,83994,83994,83994,83994,83994

In [17]:
inp_med_df.groupby(['AMOUNTUOM']).count()

,hadm_id,starttime,endtime,age,dayHrs,nightHrs,intime,los,icustay_id,ROW_ID,...,SECONDARYORDERCATEGORYNAME,ORDERCOMPONENTTYPEDESCRIPTION,ORDERCATEGORYDESCRIPTION,PATIENTWEIGHT,TOTALAMOUNT,TOTALAMOUNTUOM,STATUSDESCRIPTION,sed_flag,LABEL,nmb_flag
AMOUNTUOM,,,,,,,,,,,,,,,,,,,,,
mcg,24272,24272,24272,24272,24272,24272,24272,24272,24272,24272,...,4333,24272,24272,24272,4333,4333,24272,24272,24272,24272
mg,111728,111728,111728,111728,111728,111728,111728,111728,111728,111728,...,79661,111728,111728,111728,79661,79661,111728,111728,111728,111728

In [22]:
inp_med_df.groupby(['ORDERCATEGORYNAME']).count()

,hadm_id,starttime,endtime,age,dayHrs,nightHrs,intime,los,icustay_id,ROW_ID,...,ORDERCOMPONENTTYPEDESCRIPTION,ORDERCATEGORYDESCRIPTION,PATIENTWEIGHT,TOTALAMOUNT,TOTALAMOUNTUOM,STATUSDESCRIPTION,sed_flag,LABEL,nmb_flag,In_timeframe
ORDERCATEGORYNAME,,,,,,,,,,,,,,,,,,,,,
01-Drips,83994,83994,83994,83994,83994,83994,83994,83994,83994,83994,...,83994,83994,83994,83994,83994,83994,83994,83994,83994,73966
05-Med Bolus,52006,52006,52006,52006,52006,52006,52006,52006,52006,52006,...,52006,52006,52006,0,0,52006,52006,52006,52006,42150

## Adapters

In [10]:
med_analyze = med_etl.sedShiftTotal()

### Keeping meds during vent period

In [16]:
med_data = med_analyze.filter_by_duration(inp_med_df)
med_data.shape

(116116, 34)

In [17]:
#Saving
med_data.to_csv('170415_Medlist4_vent_duration.csv')

## *Reading Saved File*

In [2]:
med_data = pd.read_csv('170415_Medlist4_vent_duration.csv', 
                       parse_dates=['starttime', 'endtime','STARTTIME', 'ENDTIME','intime'])
med_data.shape

(116116, 35)

In [3]:
bolus_rows = med_data.loc[med_data['ORDERCATEGORYNAME'] == '05-Med Bolus']
bolus_rows.shape

(42150, 35)

In [19]:
bolus_meds = med_analyze.get_bolus_shift_total(bolus_rows)
bolus_meds.shape

//anaconda/envs/py27/lib/python2.7/site-packages/pandas/core/indexing.py:297: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
//anaconda/envs/py27/lib/python2.7/site-packages/pandas/core/indexing.py:477: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
Sedative_daily_totals_etl.py:196: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  med_data['norm_amount'] = med_data['norm_amount'].fillna(value = med_data['AMOUNT'])
Sedative_daily_totals_etl.py:202: FutureWarning: how in .resample() is deprecated
the new syntax is .resample(...).sum()
  med_data_hourly = med_data_unstack.resample(rule='1H', how='sum', label='right')

KeyboardInterrupt:

In [25]:
bolus_meds.head()

LABEL,Cisatracurium,Diazepam (Valium),Fentanyl,Hydromorphone (Dilaudid),Lorazepam (Ativan),Meperidine (Demerol),Methadone Hydrochloride,Midazolam (Versed),Morphine Sulfate,Propofol,Vecuronium
Shift_Start,,,,,,,,,,,
2100-08-11 07:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,NaN
2100-08-11 19:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.000001,NaN,NaN
2100-08-12 07:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,NaN,NaN
2100-08-12 19:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2100-08-13 07:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get list of encounters

In [4]:
len(med_data['ICUSTAY_ID'].unique())

2277

In [5]:
filter_cohort = med_data['ICUSTAY_ID'].unique()
filter_cohort[143:147]

array([ 286773.,  272655.,  295233.,  273364.])

In [6]:
filter_cohort_list = list(filter_cohort)

# Testing Code

In [28]:
sub_med_data = med_data.loc[med_data['ICUSTAY_ID'] == 205250]
sub_med_data.shape

(182, 35)

In [8]:
def dn_totals(med_df):
    if type(med_df.index[0]) is not pd.tslib.Timestamp:
        med_df.set_index('Shift_Start', drop=False, inplace=True)
    col_list = med_df.columns
    med_day = med_df[med_df.index.hour == 7]
    med_night = med_df[med_df.index.hour == 19]
    med_totals = {}
    for col in col_list:
        if col != 'Shift_Start':
            key1 = 'D_'+ col
            med_totals[key1] = med_day[col].sum()
            key2 = 'N_'+col
            med_totals[key2] = med_night[col].sum()
    return med_totals

In [29]:
med_bolus_df = sub_med_data.loc[sub_med_data['ORDERCATEGORYNAME'] == '05-Med Bolus']
med_iv_df = sub_med_data.loc[sub_med_data['ORDERCATEGORYNAME'] == '01-Drips']
if med_bolus_df.shape[0] > 0:
    bolus_shift_totals = med_analyze.get_bolus_shift_total(med_bolus_df)
    totals_dict = dn_totals(bolus_shift_totals)
    #cohort_bolus_totals['Hadm_id'].loc[i] = hadm_id

In [30]:
totals_dict

{'D_Fentanyl': -0.37500000000000011,
 'D_Midazolam (Versed)': -26.000001399999995,
 'D_Morphine Sulfate': 8.0000003999999993,
 'D_Propofol': nan,
 'N_Fentanyl': 1.2749999644999999,
 'N_Midazolam (Versed)': 31.500000539999998,
 'N_Morphine Sulfate': nan,
 'N_Propofol': 30.000003}

In [12]:
totals_dict

{'D_Fentanyl': 0.71699997999999998,
 'D_Midazolam (Versed)': 22.000001099999999,
 'D_Morphine Sulfate': 2.0000000999999998,
 'N_Fentanyl': 0.154999993,
 'N_Midazolam (Versed)': 14.0000006,
 'N_Morphine Sulfate': nan}

In [13]:
if med_iv_df.shape[0] > 0:
    iv_shift_totals = med_analyze.get_IV_shift_total(med_iv_df)
    if iv_shift_totals.shape[0] > 0:
        total_iv_dict = dn_totals(iv_shift_totals)

Sedative_daily_totals_etl.py:220: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  med_data['norm_rate'] = np.nan
Sedative_daily_totals_etl.py:226: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  med_data['norm_rate'] = med_data['norm_rate'].fillna(value = med_data['RATE'])

In [28]:
iv_shift_totals

label,Fentanyl,Fentanyl (Concentrate),Midazolam (Versed),Morphine Sulfate
Shift_Start,,,,
2167-12-23 19:00:00,0.089074,NaN,29.000003,NaN
2167-12-24 07:00:00,0.176587,NaN,17.137574,NaN
2167-12-24 19:00:00,0.360096,NaN,61.010758,NaN
2167-12-25 07:00:00,0.102861,NaN,21.824500,NaN
2167-12-25 19:00:00,0.255000,NaN,33.019546,NaN
2167-12-26 07:00:00,0.255000,NaN,28.665740,NaN
2167-12-26 19:00:00,0.097133,NaN,12.069915,NaN
2167-12-27 07:00:00,0.302841,NaN,33.844336,NaN
2167-12-27 19:00:00,0.210247,NaN,17.212898,NaN
2167-12-28 07:00:00,0.511148,NaN,48.093458,NaN
2167-12-28 19:00:00,0.513712,NaN,49.829664,NaN
2167-12-29 07:00:00,0.367144,NaN,48.233362,NaN
2167-12-29 19:00:00,0.557935,NaN,48.418198,NaN
2167-12-30 07:00:00,0.612233,NaN,48.371028,NaN
2167-12-30 19:00:00,0.601393,NaN,48.439525,NaN
2167-12-31 07:00:00,0.608165,NaN,48.627299,NaN
2167-12-31 19:00:00,0.776163,-0.001670,48.756670,NaN
2168-01-01 07:00:00,NaN,1.202410,23.371440,NaN
2168-01-01 19:00:00,NaN,0.578257,48.538543,NaN
2168-01-02 07:00:00,NaN,0.836034,48.561373,NaN
2168-01-02 19:00:00,NaN,1.203217,48.280867,NaN
2168-01-03 07:00:00,NaN,0.570129,48.191542,NaN
2168-01-03 19:00:00,NaN,1.121437,49.387874,NaN
2168-01-04 07:00:00,NaN,0.464190,55.683164,NaN
2168-01-04 19:00:00,NaN,0.576418,18.716398,NaN
2168-01-05 07:00:00,NaN,0.319179,14.240014,NaN
2168-01-05 19:00:00,NaN,1.208889,44.420166,NaN
2168-01-06 07:00:00,NaN,0.627967,33.945457,NaN
2168-01-06 19:00:00,NaN,1.253402,42.452695,NaN
2168-01-07 07:00:00,NaN,0.417843,28.953799,-0.927469
2168-01-07 19:00:00,NaN,0.202672,34.186192,60.111112

In [14]:
iv_shift_totals

label,Fentanyl,Fentanyl (Concentrate),Midazolam (Versed),Morphine Sulfate
Shift_Start,,,,
2167-12-23 19:00:00,0.089074,NaN,29.000003,NaN
2167-12-24 07:00:00,0.176587,NaN,17.137574,NaN
2167-12-24 19:00:00,0.360096,NaN,61.010758,NaN
2167-12-25 07:00:00,0.308582,NaN,25.404798,NaN
2167-12-25 19:00:00,0.255000,NaN,22.666866,NaN
2167-12-26 07:00:00,0.255000,NaN,28.665740,NaN
2167-12-26 19:00:00,0.097133,NaN,12.069915,NaN
2167-12-27 07:00:00,0.302841,NaN,33.844336,NaN
2167-12-27 19:00:00,0.210247,NaN,17.212898,NaN
2167-12-28 07:00:00,0.511148,NaN,48.093458,NaN
2167-12-28 19:00:00,0.513712,NaN,49.829664,NaN
2167-12-29 07:00:00,0.514002,NaN,48.233362,NaN
2167-12-29 19:00:00,0.398525,NaN,48.418198,NaN
2167-12-30 07:00:00,0.612233,NaN,48.371028,NaN
2167-12-30 19:00:00,0.601393,NaN,48.439525,NaN
2167-12-31 07:00:00,0.608165,NaN,48.627299,NaN
2167-12-31 19:00:00,0.776163,NaN,48.756670,NaN
2168-01-01 07:00:00,NaN,1.200740,23.371440,NaN
2168-01-01 19:00:00,NaN,1.202410,48.538543,NaN
2168-01-02 07:00:00,NaN,0.604078,48.561373,NaN
2168-01-02 19:00:00,NaN,1.203217,48.280867,NaN
2168-01-03 07:00:00,NaN,0.570129,48.191542,NaN
2168-01-03 19:00:00,NaN,1.121437,49.387874,NaN
2168-01-04 07:00:00,NaN,0.464190,55.683164,NaN
2168-01-04 19:00:00,NaN,0.576418,22.216222,NaN
2168-01-05 07:00:00,NaN,0.319179,12.793043,NaN
2168-01-05 19:00:00,NaN,1.208889,44.420166,NaN
2168-01-06 07:00:00,NaN,0.627967,33.945457,NaN
2168-01-06 19:00:00,NaN,1.253402,42.452695,NaN
2168-01-07 07:00:00,NaN,0.417843,28.953799,4.000000
2168-01-07 19:00:00,NaN,0.202672,34.186192,27.128087

In [29]:
total_iv_dict

{'D_Fentanyl': 2.9359785984918574,
 'D_Fentanyl (Concentrate)': 4.4377503238499996,
 'D_Midazolam (Versed)': 547.74408608598333,
 'D_Morphine Sulfate': -0.92746938000000068,
 'N_Fentanyl': 3.4607530806402775,
 'N_Fentanyl (Concentrate)': 6.1426227567750002,
 'N_Midazolam (Versed)': 633.73991099943646,
 'N_Morphine Sulfate': 60.111111600000001}

In [15]:
total_iv_dict

{'D_Fentanyl': 3.2885577196690003,
 'D_Fentanyl (Concentrate)': 4.20412436295,
 'D_Midazolam (Versed)': 549.87741320853888,
 'D_Morphine Sulfate': 3.9999998400000005,
 'N_Fentanyl': 3.3013431620288491,
 'N_Fentanyl (Concentrate)': 6.7684451427750005,
 'N_Midazolam (Versed)': 626.88705488126982,
 'N_Morphine Sulfate': 27.128086500000002}

In [67]:
a = pd.DataFrame(total_iv_dict.items(), columns = ['Med', 'Amount (mg)'])
a['ICU_ID'] = filter_cohort_list[25]

In [68]:
a = a.groupby(['ICU_ID', 'Med']).mean()
a = a.unstack()

In [69]:
a

         Amount (mg)                                                \
Med       D_Fentanyl D_Fentanyl (Concentrate) D_Midazolam (Versed)
ICU_ID
233344.0    2.935979                  4.43775           547.744086

                                                                 \
Med      D_Morphine Sulfate N_Fentanyl N_Fentanyl (Concentrate)
ICU_ID
233344.0          -0.927469   3.460753                 6.142623


Med      N_Midazolam (Versed) N_Morphine Sulfate
ICU_ID
233344.0           633.739911          60.111112

### Negative values

In [16]:
med_iv_df.shape

(144, 36)

In [17]:
morph_rows = med_iv_df.loc[med_iv_df['LABEL'] == 'Morphine Sulfate']
morph_rows

,Unnamed: 0,hadm_id,starttime,endtime,age,dayHrs,nightHrs,intime,los,icustay_id,...,ORDERCATEGORYDESCRIPTION,PATIENTWEIGHT,TOTALAMOUNT,TOTALAMOUNTUOM,STATUSDESCRIPTION,sed_flag,LABEL,nmb_flag,In_timeframe,norm_rate
1190,1472,185644,2167-12-23 21:00:00,2168-01-07 20:00:00,73,180.0,179.0,2167-12-23 20:54:37,15.3674,226056,...,Continuous Med,95.8,100.0,ml,Changed,0.0,Morphine Sulfate,0,1.0,10.000000
1192,1478,185644,2167-12-23 21:00:00,2168-01-07 20:00:00,73,180.0,179.0,2167-12-23 20:54:37,15.3674,226056,...,Continuous Med,95.8,100.0,ml,Changed,0.0,Morphine Sulfate,0,1.0,20.037037

In [73]:
iv_shift_totals

label,Fentanyl,Fentanyl (Concentrate),Midazolam (Versed),Morphine Sulfate
Shift_Start,,,,
2167-12-23 19:00:00,0.089074,NaN,29.000003,NaN
2167-12-24 07:00:00,0.176587,NaN,17.137574,NaN
2167-12-24 19:00:00,0.360096,NaN,61.010758,NaN
2167-12-25 07:00:00,0.102861,NaN,21.824500,NaN
2167-12-25 19:00:00,0.255000,NaN,33.019546,NaN
2167-12-26 07:00:00,0.255000,NaN,28.665740,NaN
2167-12-26 19:00:00,0.097133,NaN,12.069915,NaN
2167-12-27 07:00:00,0.302841,NaN,33.844336,NaN
2167-12-27 19:00:00,0.210247,NaN,17.212898,NaN
2167-12-28 07:00:00,0.511148,NaN,48.093458,NaN
2167-12-28 19:00:00,0.513712,NaN,49.829664,NaN
2167-12-29 07:00:00,0.367144,NaN,48.233362,NaN
2167-12-29 19:00:00,0.557935,NaN,48.418198,NaN
2167-12-30 07:00:00,0.612233,NaN,48.371028,NaN
2167-12-30 19:00:00,0.601393,NaN,48.439525,NaN
2167-12-31 07:00:00,0.608165,NaN,48.627299,NaN
2167-12-31 19:00:00,0.776163,-0.001670,48.756670,NaN
2168-01-01 07:00:00,NaN,1.202410,23.371440,NaN
2168-01-01 19:00:00,NaN,0.578257,48.538543,NaN
2168-01-02 07:00:00,NaN,0.836034,48.561373,NaN
2168-01-02 19:00:00,NaN,1.203217,48.280867,NaN
2168-01-03 07:00:00,NaN,0.570129,48.191542,NaN
2168-01-03 19:00:00,NaN,1.121437,49.387874,NaN
2168-01-04 07:00:00,NaN,0.464190,55.683164,NaN
2168-01-04 19:00:00,NaN,0.576418,18.716398,NaN
2168-01-05 07:00:00,NaN,0.319179,14.240014,NaN
2168-01-05 19:00:00,NaN,1.208889,44.420166,NaN
2168-01-06 07:00:00,NaN,0.627967,33.945457,NaN
2168-01-06 19:00:00,NaN,1.253402,42.452695,NaN
2168-01-07 07:00:00,NaN,0.417843,28.953799,-0.927469
2168-01-07 19:00:00,NaN,0.202672,34.186192,60.111112

## Debugging

In [18]:
d_breaks = med_analyze._shift_IV_amt(morph_rows['STARTTIME'].iloc[0], morph_rows['ENDTIME'].iloc[0])
d_breaks

[Timedelta('0 days 00:24:00'), Timedelta('0 days 00:35:00')]

In [35]:
morph_rows[['ICUSTAY_ID','STARTTIME', 'ENDTIME', 'intime', 'starttime', 'endtime', 'LABEL', 'RATE', 'RATEUOM']]

,ICUSTAY_ID,STARTTIME,ENDTIME,intime,starttime,endtime,LABEL,RATE,RATEUOM
1472,226056.0,2168-01-07 18:36:00,2168-01-07 19:35:00,2167-12-23 20:54:37,2167-12-23 21:00:00,2168-01-07 20:00:00,Morphine Sulfate,10.000000,mg/hour
1478,226056.0,2168-01-07 19:35:00,2168-01-07 22:00:00,2167-12-23 20:54:37,2167-12-23 21:00:00,2168-01-07 20:00:00,Morphine Sulfate,20.037037,mg/hour

In [19]:
start_shift_start = med_analyze._shift_start_time(morph_rows['STARTTIME'].iloc[0])
start_shift_end = med_analyze._shift_end_time(morph_rows['STARTTIME'].iloc[0])
end_shift_start = med_analyze._shift_start_time(morph_rows['ENDTIME'].iloc[0])
end_shift_end = med_analyze._shift_end_time(morph_rows['ENDTIME'].iloc[0])

In [20]:
print start_shift_start, start_shift_end, end_shift_start, end_shift_end

2168-01-07 07:00:00 2168-01-07 19:00:00 2168-01-07 19:00:00 2168-01-08 07:00:00

In [21]:
timedelta(hours=morph_rows['STARTTIME'].iloc[0].hour - 7)

datetime.timedelta(0, 39600)

### Bolus Negative Values

In [33]:
prop_rows = med_bolus_df.loc[med_bolus_df['LABEL'] == 'Midazolam (Versed)']
prop_rows

,Unnamed: 0,hadm_id,starttime,endtime,age,dayHrs,nightHrs,intime,los,icustay_id,...,ORDERCATEGORYDESCRIPTION,PATIENTWEIGHT,TOTALAMOUNT,TOTALAMOUNTUOM,STATUSDESCRIPTION,sed_flag,LABEL,nmb_flag,In_timeframe,norm_amount
67069,98994,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.000000
67070,98995,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.000000
67072,98997,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.000000
67073,98998,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,2.000000
67074,98999,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.000000
67075,99000,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,Rewritten,0.0,Midazolam (Versed),0,1.0,-32.000002
67076,99001,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,2.000000
67078,99003,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.000000
67079,99004,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.000000
67080,99005,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.500000
67084,99009,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,2.000000
67085,99010,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.000000
67086,99011,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.000000
67089,99014,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.000000
67090,99015,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,0.500000
67092,99017,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.000000
67094,99019,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.000000
67095,99020,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.000000
67096,99021,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,0.500000
67097,99022,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.000000
67098,99023,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,3.000000
67108,99033,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,2.000000
67110,99035,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,2.000000
67113,99038,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.000000
67114,99039,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.000000
67117,99042,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.000000
67119,99044,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,2.000000
67120,99045,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,2.000000
67129,99054,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.000000
67131,99056,151223,2171-02-05 20:00:00,2171-02-16 17:54:00,53,130.9,131.0,2171-02-05 20:06:33,11.055,205250,...,Drug Push,94.6,NaN,NaN,FinishedRunning,0.0,Midazolam (Versed),0,1.0,1.000000

In [34]:
prop_rows[['ICUSTAY_ID','STARTTIME', 'ENDTIME', 'intime', 'starttime', 'endtime', 'LABEL', 'AMOUNT', 'AMOUNTUOM']]

,ICUSTAY_ID,STARTTIME,ENDTIME,intime,starttime,endtime,LABEL,AMOUNT,AMOUNTUOM
67069,205250.0,2171-02-12 21:16:00,2171-02-12 21:17:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.000000,mg
67070,205250.0,2171-02-09 21:38:00,2171-02-09 21:39:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.000000,mg
67072,205250.0,2171-02-09 22:02:00,2171-02-09 22:03:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.000000,mg
67073,205250.0,2171-02-08 02:02:00,2171-02-08 02:03:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),2.000000,mg
67074,205250.0,2171-02-14 03:00:00,2171-02-14 03:01:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.000000,mg
67075,205250.0,2171-02-07 17:30:00,2171-02-07 17:14:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),-32.000002,mg
67076,205250.0,2171-02-09 20:37:00,2171-02-09 20:38:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),2.000000,mg
67078,205250.0,2171-02-11 03:30:00,2171-02-11 03:31:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.000000,mg
67079,205250.0,2171-02-14 03:51:00,2171-02-14 03:52:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.000000,mg
67080,205250.0,2171-02-08 20:00:00,2171-02-08 20:01:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.500000,mg
67084,205250.0,2171-02-10 14:41:00,2171-02-10 14:42:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),2.000000,mg
67085,205250.0,2171-02-14 03:33:00,2171-02-14 03:34:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.000000,mg
67086,205250.0,2171-02-16 01:02:00,2171-02-16 01:03:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.000000,mg
67089,205250.0,2171-02-15 04:55:00,2171-02-15 04:56:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.000000,mg
67090,205250.0,2171-02-12 02:00:00,2171-02-12 02:01:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),0.500000,mg
67092,205250.0,2171-02-12 22:05:00,2171-02-12 22:06:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.000000,mg
67094,205250.0,2171-02-09 00:00:00,2171-02-09 00:01:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.000000,mg
67095,205250.0,2171-02-12 06:40:00,2171-02-12 06:41:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.000000,mg
67096,205250.0,2171-02-09 03:45:00,2171-02-09 03:46:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),0.500000,mg
67097,205250.0,2171-02-14 03:10:00,2171-02-14 03:11:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.000000,mg
67098,205250.0,2171-02-07 18:15:00,2171-02-07 18:16:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),3.000000,mg
67108,205250.0,2171-02-07 01:25:00,2171-02-07 01:26:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),2.000000,mg
67110,205250.0,2171-02-07 22:30:00,2171-02-07 22:31:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),2.000000,mg
67113,205250.0,2171-02-15 20:00:00,2171-02-15 20:01:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.000000,mg
67114,205250.0,2171-02-07 21:36:00,2171-02-07 21:37:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.000000,mg
67117,205250.0,2171-02-13 05:27:00,2171-02-13 05:28:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.000000,mg
67119,205250.0,2171-02-07 01:05:00,2171-02-07 01:06:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),2.000000,mg
67120,205250.0,2171-02-07 16:30:00,2171-02-07 16:31:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),2.000000,mg
67129,205250.0,2171-02-10 06:00:00,2171-02-10 06:01:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.000000,mg
67131,205250.0,2171-02-10 20:09:00,2171-02-10 20:10:00,2171-02-05 20:06:33,2171-02-05 20:00:00,2171-02-16 17:54:00,Midazolam (Versed),1.000000,mg