# Notebook for analyzing unit- wise sedative stats
- Erina Ghosh 170716

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

Reading cohort file

In [2]:
cohort_df = pd.read_csv('cohort2474.csv')
cohort_df.head()

,Unnamed: 0,subject_id,icustay_id,ventnum,starttime,endtime,duration_hours,age,rank,dayHrs,nightHrs,hadm_id,first_careunit,last_careunit,intime,outtime,los
0,1,10075,263099,1,2184-10-04 12:00:00,2184-10-08 16:00:00,100.00,62,1,52.00,48.0,153175,CSRU,CSRU,2184-10-04 09:03:19,2184-10-08 17:44:15,4.3618
1,2,10248,215903,1,2175-06-10 00:00:00,2175-06-13 16:00:00,88.00,69,1,45.00,43.0,108856,MICU,MICU,2175-06-09 18:32:51,2175-06-15 16:21:26,5.9087
2,3,10675,250919,1,2114-11-12 10:00:00,2114-11-22 12:00:00,242.00,56,1,122.00,120.0,195182,MICU,MICU,2114-11-09 15:37:51,2114-11-22 14:47:47,12.9652
3,4,10721,260189,1,2192-04-13 08:00:00,2192-04-21 12:00:00,196.00,36,1,100.00,96.0,128647,MICU,MICU,2192-04-12 16:45:48,2192-04-21 14:30:58,8.9064
4,5,11019,299133,1,2132-06-09 13:09:00,2132-06-17 08:00:00,186.85,58,1,90.85,96.0,194301,MICU,MICU,2132-06-09 12:50:20,2132-06-17 17:49:12,8.2075

Reading med total file

In [38]:
cohort_med_total = pd.read_csv('170726_cohort_IV_bolus_total.csv')
cohort_med_total.head()

,Unnamed: 0,D_Cisatracurium,D_Dexmedetomidine (Precedex),D_Diazepam (Valium),D_Fentanyl,D_Fentanyl (Concentrate),D_Hydromorphone (Dilaudid),D_Lorazepam (Ativan),D_Meperidine (Demerol),D_Methadone Hydrochloride,...,N_Fentanyl,N_Fentanyl (Concentrate),N_Hydromorphone (Dilaudid),N_Lorazepam (Ativan),N_Meperidine (Demerol),N_Methadone Hydrochloride,N_Midazolam (Versed),N_Morphine Sulfate,N_Propofol,N_Vecuronium
0,200063.0,NaN,0.422764,NaN,NaN,NaN,NaN,NaN,25.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,25.000002,3072.541369,NaN
1,200069.0,NaN,NaN,NaN,0.075,NaN,4.0,NaN,NaN,NaN,...,0.075,NaN,3.0,NaN,NaN,NaN,NaN,NaN,456.000000,NaN
2,200087.0,NaN,NaN,NaN,0.425,1.325515,4.0,NaN,NaN,NaN,...,0.575,1.641358,3.0,NaN,NaN,NaN,26.723236,NaN,NaN,NaN
3,200282.0,NaN,NaN,NaN,1.025,2.571735,NaN,NaN,NaN,NaN,...,0.575,2.184793,NaN,NaN,NaN,NaN,81.844142,NaN,NaN,NaN
4,200339.0,NaN,0.215285,NaN,NaN,NaN,NaN,19.000001,NaN,NaN,...,NaN,NaN,NaN,43.000002,NaN,NaN,NaN,NaN,3847.995546,NaN

### Merging last care unit & duration of ventilation with med total file. Unnamed: 0 is the ICU stay ID

In [39]:
cohort_unit = cohort_df[['icustay_id', 'last_careunit', 'dayHrs', 'nightHrs']].copy()

In [40]:
cohort_med_hour = pd.merge(cohort_med_total, cohort_unit, left_on='Unnamed: 0', right_on= 'icustay_id', how = 'left')
cohort_med_hour.head()

,Unnamed: 0,D_Cisatracurium,D_Dexmedetomidine (Precedex),D_Diazepam (Valium),D_Fentanyl,D_Fentanyl (Concentrate),D_Hydromorphone (Dilaudid),D_Lorazepam (Ativan),D_Meperidine (Demerol),D_Methadone Hydrochloride,...,N_Meperidine (Demerol),N_Methadone Hydrochloride,N_Midazolam (Versed),N_Morphine Sulfate,N_Propofol,N_Vecuronium,icustay_id,last_careunit,dayHrs,nightHrs
0,200063.0,NaN,0.422764,NaN,NaN,NaN,NaN,NaN,25.0,NaN,...,NaN,NaN,8.000000,25.000002,3072.541369,NaN,200063,CSRU,72.5,71.50
1,200069.0,NaN,NaN,NaN,0.075,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,456.000000,NaN,200069,SICU,33.0,28.75
2,200087.0,NaN,NaN,NaN,0.425,1.325515,4.0,NaN,NaN,NaN,...,NaN,NaN,26.723236,NaN,NaN,NaN,200087,MICU,46.0,48.00
3,200282.0,NaN,NaN,NaN,1.025,2.571735,NaN,NaN,NaN,NaN,...,NaN,NaN,81.844142,NaN,NaN,NaN,200282,TSICU,111.0,109.00
4,200339.0,NaN,0.215285,NaN,NaN,NaN,NaN,19.000001,NaN,NaN,...,NaN,NaN,NaN,NaN,3847.995546,NaN,200339,SICU,117.9,120.00

In [41]:
cohort_med_hour.shape

(2277, 31)

### Calculating average dose (mg/ hr)

In [42]:
col_list = cohort_med_total.columns
len(col_list)

27

In [43]:
for col in col_list:
    if 'D_' in col:
        cohort_med_hour[col] = cohort_med_hour[col]/cohort_med_hour['dayHrs']
    elif 'N_' in col:
        cohort_med_hour[col] = cohort_med_hour[col]/cohort_med_hour['nightHrs']

In [44]:
cohort_med_hour.head()

,Unnamed: 0,D_Cisatracurium,D_Dexmedetomidine (Precedex),D_Diazepam (Valium),D_Fentanyl,D_Fentanyl (Concentrate),D_Hydromorphone (Dilaudid),D_Lorazepam (Ativan),D_Meperidine (Demerol),D_Methadone Hydrochloride,...,N_Meperidine (Demerol),N_Methadone Hydrochloride,N_Midazolam (Versed),N_Morphine Sulfate,N_Propofol,N_Vecuronium,icustay_id,last_careunit,dayHrs,nightHrs
0,200063.0,NaN,0.005831,NaN,NaN,NaN,NaN,NaN,0.344828,NaN,...,NaN,NaN,0.111888,0.34965,42.972607,NaN,200063,CSRU,72.5,71.50
1,200069.0,NaN,NaN,NaN,0.002273,NaN,0.121212,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,15.860870,NaN,200069,SICU,33.0,28.75
2,200087.0,NaN,NaN,NaN,0.009239,0.028816,0.086957,NaN,NaN,NaN,...,NaN,NaN,0.556734,NaN,NaN,NaN,200087,MICU,46.0,48.00
3,200282.0,NaN,NaN,NaN,0.009234,0.023169,NaN,NaN,NaN,NaN,...,NaN,NaN,0.750864,NaN,NaN,NaN,200282,TSICU,111.0,109.00
4,200339.0,NaN,0.001826,NaN,NaN,NaN,NaN,0.161154,NaN,NaN,...,NaN,NaN,NaN,NaN,32.066630,NaN,200339,SICU,117.9,120.00

### Grouping by care unit

In [45]:
unit_med_count = cohort_med_hour.groupby(['last_careunit']).count()
unit_med_count

,Unnamed: 0,D_Cisatracurium,D_Dexmedetomidine (Precedex),D_Diazepam (Valium),D_Fentanyl,D_Fentanyl (Concentrate),D_Hydromorphone (Dilaudid),D_Lorazepam (Ativan),D_Meperidine (Demerol),D_Methadone Hydrochloride,...,N_Lorazepam (Ativan),N_Meperidine (Demerol),N_Methadone Hydrochloride,N_Midazolam (Versed),N_Morphine Sulfate,N_Propofol,N_Vecuronium,icustay_id,dayHrs,nightHrs
last_careunit,,,,,,,,,,,,,,,,,,,,,
CCU,130,0,3,2,83,62,3,10,1,0,...,12,0,0,92,22,65,0,130,130,130
CSRU,758,0,140,2,123,45,85,54,37,1,...,50,43,0,77,599,744,5,758,758,758
MICU,640,1,47,30,469,327,52,109,3,10,...,113,3,11,444,117,383,6,640,640,640
SICU,408,1,30,9,247,105,139,67,1,4,...,75,3,2,119,89,354,4,408,408,408
TSICU,341,2,34,12,284,164,159,81,3,7,...,91,1,5,128,39,302,3,341,341,341

In [46]:
unit_med_avg = cohort_med_hour.groupby(['last_careunit']).median()

In [47]:
unit_med_avg

,Unnamed: 0,D_Cisatracurium,D_Dexmedetomidine (Precedex),D_Diazepam (Valium),D_Fentanyl,D_Fentanyl (Concentrate),D_Hydromorphone (Dilaudid),D_Lorazepam (Ativan),D_Meperidine (Demerol),D_Methadone Hydrochloride,...,N_Lorazepam (Ativan),N_Meperidine (Demerol),N_Methadone Hydrochloride,N_Midazolam (Versed),N_Morphine Sulfate,N_Propofol,N_Vecuronium,icustay_id,dayHrs,nightHrs
last_careunit,,,,,,,,,,,,,,,,,,,,,
CCU,249324.5,NaN,0.001081,0.629310,0.002083,0.013786,0.043210,0.011848,0.312500,NaN,...,0.013396,NaN,NaN,0.503655,0.055556,6.231574,NaN,249324,50.291667,49.95
CSRU,250478.0,NaN,0.001150,0.126324,0.003448,0.009927,0.018779,0.026145,0.312500,0.068902,...,0.030331,0.347222,NaN,0.111888,0.166667,5.660046,0.277778,250478,36.000000,36.00
MICU,252300.5,0.108460,0.001570,0.275541,0.004950,0.020886,0.044814,0.020067,0.132979,0.623736,...,0.020833,0.271739,0.666667,0.641045,0.104167,11.392990,0.246309,252300,51.300000,53.00
SICU,248954.0,0.351105,0.001887,0.454545,0.003819,0.017369,0.035948,0.039394,0.151822,0.257192,...,0.027778,0.178423,0.422581,0.318399,0.192049,11.018410,0.225845,248954,49.000000,48.00
TSICU,251814.0,0.049182,0.001135,0.265838,0.008785,0.019946,0.044554,0.041667,0.304878,0.189019,...,0.042857,0.757576,0.294118,0.250713,0.107527,11.885587,0.087719,251814,48.000000,48.00

### Grouping by drug categories

In [48]:
med_groups = pd.DataFrame(columns=['icuStay', 'D_Benzo', 'N_Benzo', 'D_Opiod', 'N_Opiod', 'D_Propofol', 'N_Propofol'])
med_groups['icuStay'] = cohort_med_hour['Unnamed: 0']
med_groups.head()

    icuStay D_Benzo N_Benzo D_Opiod N_Opiod D_Propofol N_Propofol
0  200063.0     NaN     NaN     NaN     NaN        NaN        NaN
1  200069.0     NaN     NaN     NaN     NaN        NaN        NaN
2  200087.0     NaN     NaN     NaN     NaN        NaN        NaN
3  200282.0     NaN     NaN     NaN     NaN        NaN        NaN
4  200339.0     NaN     NaN     NaN     NaN        NaN        NaN

Checking for null values

In [49]:
for i, r in cohort_med_hour.iterrows():
    if not pd.isnull(cohort_med_hour.ix[i, 'D_Lorazepam (Ativan)']):
        if not pd.isnull(cohort_med_hour.ix[i, 'D_Midazolam (Versed)']):
            if not pd.isnull(cohort_med_hour.ix[i, 'D_Diazepam (Valium)']):
                med_groups.ix[i,'D_Benzo'] = cohort_med_hour.ix[i,'D_Lorazepam (Ativan)'] 
                + (cohort_med_hour.ix[i, 'D_Midazolam (Versed)']/3) 
                + (cohort_med_hour.ix[i, 'D_Diazepam (Valium)']/5)
            else:
                med_groups.ix[i,'D_Benzo'] = cohort_med_hour.ix[i,'D_Lorazepam (Ativan)'] 
                + (cohort_med_hour.ix[i, 'D_Midazolam (Versed)']/3) 
        else:
            if not pd.isnull(cohort_med_hour.ix[i, 'D_Diazepam (Valium)']):
                med_groups.ix[i,'D_Benzo'] = cohort_med_hour.ix[i,'D_Lorazepam (Ativan)']
                + (cohort_med_hour.ix[i, 'D_Diazepam (Valium)']/5)
            else:
                med_groups.ix[i,'D_Benzo'] = cohort_med_hour.ix[i,'D_Lorazepam (Ativan)'] 
    else:
        if not pd.isnull(cohort_med_hour.ix[i, 'D_Midazolam (Versed)']):
            if not pd.isnull(cohort_med_hour.ix[i, 'D_Diazepam (Valium)']):
                med_groups.ix[i,'D_Benzo'] = (cohort_med_hour.ix[i, 'D_Midazolam (Versed)']/3) 
                + (cohort_med_hour.ix[i, 'D_Diazepam (Valium)']/5)
            else:
                med_groups.ix[i,'D_Benzo'] = (cohort_med_hour.ix[i, 'D_Midazolam (Versed)']/3) 
        else:
            if not pd.isnull(cohort_med_hour.ix[i, 'D_Diazepam (Valium)']):
                med_groups.ix[i,'D_Benzo'] = (cohort_med_hour.ix[i, 'D_Diazepam (Valium)']/5)
            else:
                med_groups.ix[i,'D_Benzo'] = np.NaN

In [50]:
med_groups.head()

    icuStay    D_Benzo N_Benzo D_Opiod N_Opiod D_Propofol N_Propofol
0  200063.0  0.0183908     NaN     NaN     NaN        NaN        NaN
1  200069.0        NaN     NaN     NaN     NaN        NaN        NaN
2  200087.0   0.172506     NaN     NaN     NaN        NaN        NaN
3  200282.0   0.268944     NaN     NaN     NaN        NaN        NaN
4  200339.0   0.161154     NaN     NaN     NaN        NaN        NaN

In [51]:
med_groups['D_Benzo'].describe()

count     1065.0
unique    1004.0
top          0.0
freq        22.0
Name: D_Benzo, dtype: float64

In [52]:
for i, r in cohort_med_hour.iterrows():
    if not pd.isnull(cohort_med_hour.ix[i, 'N_Lorazepam (Ativan)']):
        if not pd.isnull(cohort_med_hour.ix[i, 'N_Midazolam (Versed)']):
            if not pd.isnull(cohort_med_hour.ix[i, 'N_Diazepam (Valium)']):
                med_groups.ix[i,'N_Benzo'] = cohort_med_hour.ix[i,'N_Lorazepam (Ativan)'] 
                + (cohort_med_hour.ix[i, 'N_Midazolam (Versed)']/3) 
                + (cohort_med_hour.ix[i, 'N_Diazepam (Valium)']/5)
            else:
                med_groups.ix[i,'N_Benzo'] = cohort_med_hour.ix[i,'N_Lorazepam (Ativan)'] 
                + (cohort_med_hour.ix[i, 'N_Midazolam (Versed)']/3) 
        else:
            if not pd.isnull(cohort_med_hour.ix[i, 'N_Diazepam (Valium)']):
                med_groups.ix[i,'N_Benzo'] = cohort_med_hour.ix[i,'N_Lorazepam (Ativan)']
                + (cohort_med_hour.ix[i, 'N_Diazepam (Valium)']/5)
            else:
                med_groups.ix[i,'N_Benzo'] = cohort_med_hour.ix[i,'N_Lorazepam (Ativan)'] 
    else:
        if not pd.isnull(cohort_med_hour.ix[i, 'N_Midazolam (Versed)']):
            if not pd.isnull(cohort_med_hour.ix[i, 'N_Diazepam (Valium)']):
                med_groups.ix[i,'N_Benzo'] = (cohort_med_hour.ix[i, 'N_Midazolam (Versed)']/3) 
                + (cohort_med_hour.ix[i, 'N_Diazepam (Valium)']/5)
            else:
                med_groups.ix[i,'N_Benzo'] = (cohort_med_hour.ix[i, 'N_Midazolam (Versed)']/3) 
        else:
            if not pd.isnull(cohort_med_hour.ix[i, 'N_Diazepam (Valium)']):
                med_groups.ix[i,'N_Benzo'] = (cohort_med_hour.ix[i, 'N_Diazepam (Valium)']/5)
            else:
                med_groups.ix[i,'N_Benzo'] = np.NaN

In [53]:
med_groups.head()

    icuStay    D_Benzo   N_Benzo D_Opiod N_Opiod D_Propofol N_Propofol
0  200063.0  0.0183908  0.037296     NaN     NaN        NaN        NaN
1  200069.0        NaN       NaN     NaN     NaN        NaN        NaN
2  200087.0   0.172506  0.185578     NaN     NaN        NaN        NaN
3  200282.0   0.268944  0.250288     NaN     NaN        NaN        NaN
4  200339.0   0.161154  0.358333     NaN     NaN        NaN        NaN

In [54]:
med_groups['N_Benzo'].describe()

count     1054.0
unique     955.0
top          0.0
freq        29.0
Name: N_Benzo, dtype: float64

In [55]:
med_groups['N_Benzo'].median()

0.08333333333333333

### Opiods

In [56]:
for i, r in cohort_med_hour.iterrows():
    if not pd.isnull(r['D_Morphine Sulfate']):
        if not pd.isnull(r['D_Fentanyl']):
            if not pd.isnull(r['D_Fentanyl (Concentrate)']):
                if not pd.isnull(r['D_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'D_Opiod'] = r['D_Morphine Sulfate'] 
                    + (r['D_Fentanyl']/0.01) + (r['D_Fentanyl (Concentrate)']/0.01)
                    + (r['D_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'D_Opiod'] = r['D_Morphine Sulfate'] 
                    + (r['D_Fentanyl']/0.01) + (r['D_Fentanyl (Concentrate)']/0.01)
            else:
                if not pd.isnull(r['D_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'D_Opiod'] = r['D_Morphine Sulfate'] 
                    + (r['D_Fentanyl']/0.01)
                    + (r['D_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'D_Opiod'] = r['D_Morphine Sulfate'] 
                    + (r['D_Fentanyl']/0.01) 
        else:
            if not pd.isnull(r['D_Fentanyl (Concentrate)']):
                if not pd.isnull(r['D_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'D_Opiod'] = r['D_Morphine Sulfate'] 
                    + (r['D_Fentanyl (Concentrate)']/0.01)
                    + (r['D_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'D_Opiod'] = r['D_Morphine Sulfate'] 
                    + (r['D_Fentanyl (Concentrate)']/0.01)
            else:
                if not pd.isnull(r['D_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'D_Opiod'] = r['D_Morphine Sulfate'] 
                    + (r['D_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'D_Opiod'] = r['D_Morphine Sulfate']
    else:
        if not pd.isnull(r['D_Fentanyl']):
            if not pd.isnull(r['D_Fentanyl (Concentrate)']):
                if not pd.isnull(r['D_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'D_Opiod'] = (r['D_Fentanyl']/0.01) 
                    + (r['D_Fentanyl (Concentrate)']/0.01)
                    + (r['D_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'D_Opiod'] =(r['D_Fentanyl']/0.01) 
                    + (r['D_Fentanyl (Concentrate)']/0.01)
            else:
                if not pd.isnull(r['D_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'D_Opiod'] = (r['D_Fentanyl']/0.01)
                    + (r['D_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'D_Opiod'] = (r['D_Fentanyl']/0.01) 
        else:
            if not pd.isnull(r['D_Fentanyl (Concentrate)']):
                if not pd.isnull(r['D_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'D_Opiod'] = (r['D_Fentanyl (Concentrate)']/0.01)
                    + (r['D_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'D_Opiod'] = (r['D_Fentanyl (Concentrate)']/0.01)
            else:
                if not pd.isnull(r['D_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'D_Opiod'] = (r['D_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'D_Opiod'] = np.NAN

In [57]:
med_groups.head()

    icuStay    D_Benzo   N_Benzo   D_Opiod N_Opiod D_Propofol N_Propofol
0  200063.0  0.0183908  0.037296  0.344828     NaN        NaN        NaN
1  200069.0        NaN       NaN  0.227273     NaN        NaN        NaN
2  200087.0   0.172506  0.185578  0.923913     NaN        NaN        NaN
3  200282.0   0.268944  0.250288  0.923423     NaN        NaN        NaN
4  200339.0   0.161154  0.358333       NaN     NaN        NaN        NaN

In [58]:
med_groups['D_Opiod'].describe()

count     2039.0
unique    1711.0
top          0.0
freq       116.0
Name: D_Opiod, dtype: float64

In [59]:
for i, r in cohort_med_hour.iterrows():
    if not pd.isnull(r['N_Morphine Sulfate']):
        if not pd.isnull(r['N_Fentanyl']):
            if not pd.isnull(r['N_Fentanyl (Concentrate)']):
                if not pd.isnull(r['N_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'N_Opiod'] = r['N_Morphine Sulfate'] 
                    + (r['N_Fentanyl']/0.01) + (r['N_Fentanyl (Concentrate)']/0.01)
                    + (r['N_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'N_Opiod'] = r['N_Morphine Sulfate'] 
                    + (r['N_Fentanyl']/0.01) + (r['N_Fentanyl (Concentrate)']/0.01)
            else:
                if not pd.isnull(r['N_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'N_Opiod'] = r['N_Morphine Sulfate'] 
                    + (r['N_Fentanyl']/0.01)
                    + (r['N_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'N_Opiod'] = r['N_Morphine Sulfate'] 
                    + (r['N_Fentanyl']/0.01) 
        else:
            if not pd.isnull(r['N_Fentanyl (Concentrate)']):
                if not pd.isnull(r['N_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'N_Opiod'] = r['N_Morphine Sulfate'] 
                    + (r['N_Fentanyl (Concentrate)']/0.01)
                    + (r['N_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'N_Opiod'] = r['N_Morphine Sulfate'] 
                    + (r['N_Fentanyl (Concentrate)']/0.01)
            else:
                if not pd.isnull(r['N_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'N_Opiod'] = r['N_Morphine Sulfate'] 
                    + (r['N_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'N_Opiod'] = r['N_Morphine Sulfate']
    else:
        if not pd.isnull(r['N_Fentanyl']):
            if not pd.isnull(r['N_Fentanyl (Concentrate)']):
                if not pd.isnull(r['N_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'N_Opiod'] = (r['N_Fentanyl']/0.01) 
                    + (r['N_Fentanyl (Concentrate)']/0.01)
                    + (r['N_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'N_Opiod'] =(r['N_Fentanyl']/0.01) 
                    + (r['N_Fentanyl (Concentrate)']/0.01)
            else:
                if not pd.isnull(r['N_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'N_Opiod'] = (r['N_Fentanyl']/0.01)
                    + (r['N_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'N_Opiod'] = (r['N_Fentanyl']/0.01) 
        else:
            if not pd.isnull(r['N_Fentanyl (Concentrate)']):
                if not pd.isnull(r['N_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'N_Opiod'] = (r['N_Fentanyl (Concentrate)']/0.01)
                    + (r['N_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'N_Opiod'] = (r['N_Fentanyl (Concentrate)']/0.01)
            else:
                if not pd.isnull(r['N_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'N_Opiod'] = (r['N_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'N_Opiod'] = np.NAN

In [60]:
med_groups.head()

    icuStay    D_Benzo   N_Benzo   D_Opiod   N_Opiod D_Propofol N_Propofol
0  200063.0  0.0183908  0.037296  0.344828   0.34965        NaN        NaN
1  200069.0        NaN       NaN  0.227273   0.26087        NaN        NaN
2  200087.0   0.172506  0.185578  0.923913   1.19792        NaN        NaN
3  200282.0   0.268944  0.250288  0.923423  0.527523        NaN        NaN
4  200339.0   0.161154  0.358333       NaN       NaN        NaN        NaN

In [61]:
med_groups['D_Propofol'] = cohort_med_hour['D_Propofol']
med_groups['N_Propofol'] = cohort_med_hour['N_Propofol']

In [62]:
med_groups['D_Dexmedetomidine (Precedex)'] = cohort_med_hour['D_Dexmedetomidine (Precedex)']
med_groups['N_Dexmedetomidine (Precedex)'] = cohort_med_hour['N_Dexmedetomidine (Precedex)']

In [63]:
med_groups.head()

,icuStay,D_Benzo,N_Benzo,D_Opiod,N_Opiod,D_Propofol,N_Propofol,D_Dexmedetomidine (Precedex),N_Dexmedetomidine (Precedex)
0,200063.0,0.0183908,0.037296,0.344828,0.34965,46.602329,42.972607,0.005831,0.005498
1,200069.0,NaN,NaN,0.227273,0.26087,2.909091,15.860870,NaN,NaN
2,200087.0,0.172506,0.185578,0.923913,1.19792,NaN,NaN,NaN,NaN
3,200282.0,0.268944,0.250288,0.923423,0.527523,NaN,NaN,NaN,NaN
4,200339.0,0.161154,0.358333,NaN,NaN,40.564085,32.066630,0.001826,0.001089

Adding ICU type

In [64]:
med_groups['last_careunit'] = cohort_med_hour['last_careunit']

In [65]:
unit_cat_ct = med_groups.groupby(['last_careunit']).count()
unit_cat_ct

,icuStay,D_Benzo,N_Benzo,D_Opiod,N_Opiod,D_Propofol,N_Propofol,D_Dexmedetomidine (Precedex),N_Dexmedetomidine (Precedex)
last_careunit,,,,,,,,,
CCU,130,99,97,108,113,65,65,3,2
CSRU,758,127,117,701,707,747,744,140,135
MICU,640,488,488,566,566,363,383,47,46
SICU,408,168,169,339,336,345,354,30,25
TSICU,341,183,183,325,324,296,302,34,26

In [66]:
unit_cat_avg = med_groups.groupby(['last_careunit']).mean()
unit_cat_avg

,icuStay,D_Propofol,N_Propofol,D_Dexmedetomidine (Precedex),N_Dexmedetomidine (Precedex)
last_careunit,,,,,
CCU,250183.046154,10.696066,9.205273,0.000980,0.001046
CSRU,250723.579156,10.694035,8.119932,0.001672,0.001591
MICU,251207.492188,15.031820,15.234859,0.002373,0.002037
SICU,250999.269608,15.071978,15.345866,0.002165,0.002488
TSICU,251399.557185,15.890733,16.833689,0.002559,0.002744

## Calculating total median dose
- Add per hour drugs groups day + night
- Calculate median

In [67]:
med_DN_total = pd.DataFrame(columns=['Propofol', 'Dexmedetomidine (Precedex)', 'Benzo', 'Opioid'])

In [68]:
med_DN_total['Propofol'] = med_groups['D_Propofol'] + med_groups['N_Propofol']
med_DN_total.head()

    Propofol Dexmedetomidine (Precedex) Benzo Opioid
0  89.574936                        NaN   NaN    NaN
1  18.769960                        NaN   NaN    NaN
2        NaN                        NaN   NaN    NaN
3        NaN                        NaN   NaN    NaN
4  72.630714                        NaN   NaN    NaN

In [69]:
med_DN_total['Dexmedetomidine (Precedex)'] = med_groups['D_Dexmedetomidine (Precedex)'] + med_groups['N_Dexmedetomidine (Precedex)']
med_DN_total['Benzo'] = med_groups['D_Benzo'] + med_groups['N_Benzo']
med_DN_total['Opioid'] = med_groups['D_Opiod'] + med_groups['N_Opiod']
med_DN_total.head()

    Propofol  Dexmedetomidine (Precedex)      Benzo    Opioid
0  89.574936                    0.011330  0.0556868  0.694478
1  18.769960                         NaN        NaN  0.488142
2        NaN                         NaN   0.358084   2.12183
3        NaN                         NaN   0.519232   1.45095
4  72.630714                    0.002915   0.519487       NaN

In [70]:
med_DN_total['icuStay'] = med_groups['icuStay']
med_DN_total['last_careunit'] = med_groups['last_careunit']
med_DN_total.head()

,Propofol,Dexmedetomidine (Precedex),Benzo,Opioid,icuStay,last_careunit
0,89.574936,0.011330,0.0556868,0.694478,200063.0,CSRU
1,18.769960,NaN,NaN,0.488142,200069.0,SICU
2,NaN,NaN,0.358084,2.12183,200087.0,MICU
3,NaN,NaN,0.519232,1.45095,200282.0,TSICU
4,72.630714,0.002915,0.519487,NaN,200339.0,SICU

Counts...

In [71]:
med_DN_total.groupby(['last_careunit']).count()

               Propofol  Dexmedetomidine (Precedex)  Benzo  Opioid  icuStay
last_careunit
CCU                  61                           2     95     108      130
CSRU                737                         108     88     684      758
MICU                342                          43    463     557      640
SICU                339                          25    147     328      408
TSICU               289                          25    159     321      341

In [72]:
med_groups.shape

(2277, 10)

In [73]:
cohort_med_total.shape

(2277, 27)

In [74]:
med_DN_total.groupby(['last_careunit']).median()

                Propofol  Dexmedetomidine (Precedex)   icuStay
last_careunit
CCU            16.070972                    0.001975  249324.5
CSRU           14.328918                    0.002445  250478.0
MICU           25.419739                    0.004337  252300.5
SICU           23.198274                    0.004517  248954.0
TSICU          27.576802                    0.003374  251814.0

In [75]:
med_DN_total.describe()

          Propofol  Dexmedetomidine (Precedex)        icuStay
count  1768.000000                  203.000000    2277.000000
mean     26.234083                    0.004170  250979.365393
std      22.620584                    0.003679   28706.635576
min       0.005790                    0.000226  200063.000000
25%       9.207791                    0.001503  225906.000000
50%      18.955112                    0.002936  251279.000000
75%      36.766839                    0.005450  276503.000000
max     137.523867                    0.026297  299872.000000

In [76]:
med_DN_total['Propofol'].median()

18.955111724740387

In [77]:
med_DN_total['Dexmedetomidine (Precedex)'].median()

0.0029355842772500005

In [78]:
med_DN_total['Benzo'].median()

0.21549078209114264

In [79]:
med_DN_total['Opioid'].median()

0.5980684749127606