# Notebook for analyzing unit- wise sedative stats
- Erina Ghosh 170716

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

Reading cohort file

In [2]:
cohort_df = pd.read_csv('cohort2474.csv')
cohort_df.head()

,Unnamed: 0,subject_id,icustay_id,ventnum,starttime,endtime,duration_hours,age,rank,dayHrs,nightHrs,hadm_id,first_careunit,last_careunit,intime,outtime,los
0,1,10075,263099,1,2184-10-04 12:00:00,2184-10-08 16:00:00,100.00,62,1,52.00,48.0,153175,CSRU,CSRU,2184-10-04 09:03:19,2184-10-08 17:44:15,4.3618
1,2,10248,215903,1,2175-06-10 00:00:00,2175-06-13 16:00:00,88.00,69,1,45.00,43.0,108856,MICU,MICU,2175-06-09 18:32:51,2175-06-15 16:21:26,5.9087
2,3,10675,250919,1,2114-11-12 10:00:00,2114-11-22 12:00:00,242.00,56,1,122.00,120.0,195182,MICU,MICU,2114-11-09 15:37:51,2114-11-22 14:47:47,12.9652
3,4,10721,260189,1,2192-04-13 08:00:00,2192-04-21 12:00:00,196.00,36,1,100.00,96.0,128647,MICU,MICU,2192-04-12 16:45:48,2192-04-21 14:30:58,8.9064
4,5,11019,299133,1,2132-06-09 13:09:00,2132-06-17 08:00:00,186.85,58,1,90.85,96.0,194301,MICU,MICU,2132-06-09 12:50:20,2132-06-17 17:49:12,8.2075

Reading med total file

In [3]:
cohort_med_total = pd.read_csv('170716_cohort_IV_bolus_total.csv')
cohort_med_total.head()

,Unnamed: 0,N_Fentanyl (Concentrate),D_Propofol,D_Fentanyl (Concentrate),N_Propofol,D_Midazolam (Versed),N_Midazolam (Versed),D_Fentanyl,N_Fentanyl,D_Dexmedetomidine (Precedex),...,D_Hydromorphone (Dilaudid),N_Hydromorphone (Dilaudid),D_Cisatracurium,N_Diazepam (Valium),N_Vecuronium,D_Meperidine (Demerol),N_Cisatracurium,D_Diazepam (Valium),D_Vecuronium,N_Meperidine (Demerol)
0,200063.0,NaN,3378.668857,NaN,3072.541369,4.000000,8.000000,NaN,NaN,0.422764,...,NaN,NaN,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN
1,200069.0,NaN,96.000000,NaN,456.000000,NaN,NaN,0.075,0.075,NaN,...,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,200087.0,1.641358,NaN,1.325515,NaN,23.805830,26.723236,0.425,0.575,NaN,...,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,200282.0,2.184793,NaN,2.571735,NaN,89.558317,81.844142,1.025,0.575,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,200339.0,NaN,4782.505606,NaN,3847.995546,NaN,NaN,NaN,NaN,0.215285,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

    Merging last care unit & duration of ventilation with med total file. Unnamed: 0 is the ICU stay ID

In [6]:
cohort_unit = cohort_df[['icustay_id', 'last_careunit', 'dayHrs', 'nightHrs']].copy()

In [7]:
cohort_med_hour = pd.merge(cohort_med_total, cohort_unit, left_on='Unnamed: 0', right_on= 'icustay_id', how = 'outer')
cohort_med_hour.head()

,Unnamed: 0,N_Fentanyl (Concentrate),D_Propofol,D_Fentanyl (Concentrate),N_Propofol,D_Midazolam (Versed),N_Midazolam (Versed),D_Fentanyl,N_Fentanyl,D_Dexmedetomidine (Precedex),...,N_Vecuronium,D_Meperidine (Demerol),N_Cisatracurium,D_Diazepam (Valium),D_Vecuronium,N_Meperidine (Demerol),icustay_id,last_careunit,dayHrs,nightHrs
0,200063.0,NaN,3378.668857,NaN,3072.541369,4.000000,8.000000,NaN,NaN,0.422764,...,NaN,25.0,NaN,NaN,NaN,NaN,200063,CSRU,72.5,71.50
1,200069.0,NaN,96.000000,NaN,456.000000,NaN,NaN,0.075,0.075,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,200069,SICU,33.0,28.75
2,200087.0,1.641358,NaN,1.325515,NaN,23.805830,26.723236,0.425,0.575,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,200087,MICU,46.0,48.00
3,200282.0,2.184793,NaN,2.571735,NaN,89.558317,81.844142,1.025,0.575,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,200282,TSICU,111.0,109.00
4,200339.0,NaN,4782.505606,NaN,3847.995546,NaN,NaN,NaN,NaN,0.215285,...,NaN,NaN,NaN,NaN,NaN,NaN,200339,SICU,117.9,120.00

### Calculating average dose (mg/ hr)

In [9]:
col_list = cohort_med_total.columns
len(col_list)

27

In [10]:
for col in col_list:
    if 'D_' in col:
        cohort_med_hour[col] = cohort_med_hour[col]/cohort_med_hour['dayHrs']
    elif 'N_' in col:
        cohort_med_hour[col] = cohort_med_hour[col]/cohort_med_hour['nightHrs']

In [11]:
cohort_med_hour.head()

,Unnamed: 0,N_Fentanyl (Concentrate),D_Propofol,D_Fentanyl (Concentrate),N_Propofol,D_Midazolam (Versed),N_Midazolam (Versed),D_Fentanyl,N_Fentanyl,D_Dexmedetomidine (Precedex),...,N_Vecuronium,D_Meperidine (Demerol),N_Cisatracurium,D_Diazepam (Valium),D_Vecuronium,N_Meperidine (Demerol),icustay_id,last_careunit,dayHrs,nightHrs
0,200063.0,NaN,46.602329,NaN,42.972607,0.055172,0.111888,NaN,NaN,0.005831,...,NaN,0.344828,NaN,NaN,NaN,NaN,200063,CSRU,72.5,71.50
1,200069.0,NaN,2.909091,NaN,15.860870,NaN,NaN,0.002273,0.002609,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,200069,SICU,33.0,28.75
2,200087.0,0.034195,NaN,0.028816,NaN,0.517518,0.556734,0.009239,0.011979,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,200087,MICU,46.0,48.00
3,200282.0,0.020044,NaN,0.023169,NaN,0.806832,0.750864,0.009234,0.005275,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,200282,TSICU,111.0,109.00
4,200339.0,NaN,40.564085,NaN,32.066630,NaN,NaN,NaN,NaN,0.001826,...,NaN,NaN,NaN,NaN,NaN,NaN,200339,SICU,117.9,120.00

### Grouping by care unit

In [12]:
unit_med_count = cohort_med_hour.groupby(['last_careunit']).count()
unit_med_count

,Unnamed: 0,N_Fentanyl (Concentrate),D_Propofol,D_Fentanyl (Concentrate),N_Propofol,D_Midazolam (Versed),N_Midazolam (Versed),D_Fentanyl,N_Fentanyl,D_Dexmedetomidine (Precedex),...,N_Diazepam (Valium),N_Vecuronium,D_Meperidine (Demerol),N_Cisatracurium,D_Diazepam (Valium),D_Vecuronium,N_Meperidine (Demerol),icustay_id,dayHrs,nightHrs
last_careunit,,,,,,,,,,,,,,,,,,,,,
CCU,114,60,64,62,64,88,87,74,80,3,...,2,0,1,0,1,0,0,146,146,146
CSRU,756,42,746,45,744,85,77,122,106,140,...,2,5,37,0,2,6,43,806,806,806
MICU,601,328,361,327,382,439,437,456,468,47,...,25,6,3,0,29,8,3,718,718,718
SICU,387,107,345,105,354,123,116,237,215,30,...,10,4,1,0,8,12,3,440,440,440
TSICU,332,162,296,164,302,131,128,282,277,34,...,14,3,3,0,12,20,1,364,364,364

In [13]:
unit_med_avg = cohort_med_hour.groupby(['last_careunit']).median()

In [14]:
unit_med_avg

,Unnamed: 0,N_Fentanyl (Concentrate),D_Propofol,D_Fentanyl (Concentrate),N_Propofol,D_Midazolam (Versed),N_Midazolam (Versed),D_Fentanyl,N_Fentanyl,D_Dexmedetomidine (Precedex),...,N_Diazepam (Valium),N_Vecuronium,D_Meperidine (Demerol),N_Cisatracurium,D_Diazepam (Valium),D_Vecuronium,N_Meperidine (Demerol),icustay_id,dayHrs,nightHrs
last_careunit,,,,,,,,,,,,,,,,,,,,,
CCU,245911.0,0.018763,7.655357,0.013786,6.253591,0.395216,0.597273,0.002388,0.002506,0.001081,...,1.157155,NaN,0.312500,NaN,0.258621,NaN,NaN,248648,48.500000,48.0
CSRU,250655.0,0.015999,8.289620,0.009927,5.660046,0.076923,0.111888,0.003510,0.004688,0.001150,...,0.208333,0.277778,0.312500,NaN,0.126324,0.147377,0.347222,250478,37.000000,36.0
MICU,252182.0,0.022929,11.715683,0.020886,11.399060,0.555599,0.650188,0.005137,0.005871,0.001570,...,0.498339,0.246309,0.132979,NaN,0.267618,0.082323,0.271739,251908,53.000000,54.0
SICU,249571.0,0.019403,11.203485,0.017369,11.018410,0.231791,0.341673,0.004082,0.003814,0.001887,...,0.315929,0.225845,0.151822,NaN,0.383523,0.084597,0.178423,248812,49.016667,49.0
TSICU,251699.0,0.021526,13.147334,0.019946,11.885587,0.217569,0.250713,0.008889,0.008854,0.001135,...,0.484297,0.087719,0.304878,NaN,0.265838,0.096172,0.757576,251583,48.000000,48.0

### Grouping by drug categories

In [15]:
med_groups = pd.DataFrame(columns=['icuStay', 'D_Benzo', 'N_Benzo', 'D_Opiod', 'N_Opiod', 'D_Propofol', 'N_Propofol'])
med_groups['icuStay'] = cohort_med_hour['Unnamed: 0']
med_groups.head()

    icuStay D_Benzo N_Benzo D_Opiod N_Opiod D_Propofol N_Propofol
0  200063.0     NaN     NaN     NaN     NaN        NaN        NaN
1  200069.0     NaN     NaN     NaN     NaN        NaN        NaN
2  200087.0     NaN     NaN     NaN     NaN        NaN        NaN
3  200282.0     NaN     NaN     NaN     NaN        NaN        NaN
4  200339.0     NaN     NaN     NaN     NaN        NaN        NaN

Checking for null values

In [21]:
for i, r in cohort_med_hour.iterrows():
    if not pd.isnull(cohort_med_hour.ix[i, 'D_Lorazepam (Ativan)']):
        if not pd.isnull(cohort_med_hour.ix[i, 'D_Midazolam (Versed)']):
            if not pd.isnull(cohort_med_hour.ix[i, 'D_Diazepam (Valium)']):
                med_groups.ix[i,'D_Benzo'] = cohort_med_hour.ix[i,'D_Lorazepam (Ativan)'] 
                + (cohort_med_hour.ix[i, 'D_Midazolam (Versed)']/3) 
                + (cohort_med_hour.ix[i, 'D_Diazepam (Valium)']/5)
            else:
                med_groups.ix[i,'D_Benzo'] = cohort_med_hour.ix[i,'D_Lorazepam (Ativan)'] 
                + (cohort_med_hour.ix[i, 'D_Midazolam (Versed)']/3) 
        else:
            if not pd.isnull(cohort_med_hour.ix[i, 'D_Diazepam (Valium)']):
                med_groups.ix[i,'D_Benzo'] = cohort_med_hour.ix[i,'D_Lorazepam (Ativan)']
                + (cohort_med_hour.ix[i, 'D_Diazepam (Valium)']/5)
            else:
                med_groups.ix[i,'D_Benzo'] = cohort_med_hour.ix[i,'D_Lorazepam (Ativan)'] 
    else:
        if not pd.isnull(cohort_med_hour.ix[i, 'D_Midazolam (Versed)']):
            if not pd.isnull(cohort_med_hour.ix[i, 'D_Diazepam (Valium)']):
                med_groups.ix[i,'D_Benzo'] = (cohort_med_hour.ix[i, 'D_Midazolam (Versed)']/3) 
                + (cohort_med_hour.ix[i, 'D_Diazepam (Valium)']/5)
            else:
                med_groups.ix[i,'D_Benzo'] = (cohort_med_hour.ix[i, 'D_Midazolam (Versed)']/3) 
        else:
            if not pd.isnull(cohort_med_hour.ix[i, 'D_Diazepam (Valium)']):
                med_groups.ix[i,'D_Benzo'] = (cohort_med_hour.ix[i, 'D_Diazepam (Valium)']/5)
            else:
                med_groups.ix[i,'D_Benzo'] = np.NaN

In [22]:
med_groups.head()

    icuStay   D_Benzo N_Benzo D_Opiod N_Opiod D_Propofol N_Propofol
0  200063.0  0.018391     NaN     NaN     NaN        NaN        NaN
1  200069.0       NaN     NaN     NaN     NaN        NaN        NaN
2  200087.0  0.172506     NaN     NaN     NaN        NaN        NaN
3  200282.0  0.268944     NaN     NaN     NaN        NaN        NaN
4  200339.0  0.161154     NaN     NaN     NaN        NaN        NaN

In [23]:
med_groups['D_Benzo'].describe()

count    1029.000000
mean        0.175145
std         0.249371
min         0.000000
25%         0.023068
50%         0.078199
75%         0.227181
max         2.594435
Name: D_Benzo, dtype: float64

In [24]:
for i, r in cohort_med_hour.iterrows():
    if not pd.isnull(cohort_med_hour.ix[i, 'N_Lorazepam (Ativan)']):
        if not pd.isnull(cohort_med_hour.ix[i, 'N_Midazolam (Versed)']):
            if not pd.isnull(cohort_med_hour.ix[i, 'N_Diazepam (Valium)']):
                med_groups.ix[i,'N_Benzo'] = cohort_med_hour.ix[i,'N_Lorazepam (Ativan)'] 
                + (cohort_med_hour.ix[i, 'N_Midazolam (Versed)']/3) 
                + (cohort_med_hour.ix[i, 'N_Diazepam (Valium)']/5)
            else:
                med_groups.ix[i,'N_Benzo'] = cohort_med_hour.ix[i,'N_Lorazepam (Ativan)'] 
                + (cohort_med_hour.ix[i, 'N_Midazolam (Versed)']/3) 
        else:
            if not pd.isnull(cohort_med_hour.ix[i, 'N_Diazepam (Valium)']):
                med_groups.ix[i,'N_Benzo'] = cohort_med_hour.ix[i,'N_Lorazepam (Ativan)']
                + (cohort_med_hour.ix[i, 'N_Diazepam (Valium)']/5)
            else:
                med_groups.ix[i,'N_Benzo'] = cohort_med_hour.ix[i,'N_Lorazepam (Ativan)'] 
    else:
        if not pd.isnull(cohort_med_hour.ix[i, 'N_Midazolam (Versed)']):
            if not pd.isnull(cohort_med_hour.ix[i, 'N_Diazepam (Valium)']):
                med_groups.ix[i,'N_Benzo'] = (cohort_med_hour.ix[i, 'N_Midazolam (Versed)']/3) 
                + (cohort_med_hour.ix[i, 'N_Diazepam (Valium)']/5)
            else:
                med_groups.ix[i,'N_Benzo'] = (cohort_med_hour.ix[i, 'N_Midazolam (Versed)']/3) 
        else:
            if not pd.isnull(cohort_med_hour.ix[i, 'N_Diazepam (Valium)']):
                med_groups.ix[i,'N_Benzo'] = (cohort_med_hour.ix[i, 'N_Diazepam (Valium)']/5)
            else:
                med_groups.ix[i,'N_Benzo'] = np.NaN

In [25]:
med_groups.head()

    icuStay   D_Benzo   N_Benzo D_Opiod N_Opiod D_Propofol N_Propofol
0  200063.0  0.018391  0.037296     NaN     NaN        NaN        NaN
1  200069.0       NaN       NaN     NaN     NaN        NaN        NaN
2  200087.0  0.172506  0.185578     NaN     NaN        NaN        NaN
3  200282.0  0.268944  0.250288     NaN     NaN        NaN        NaN
4  200339.0  0.161154  0.358333     NaN     NaN        NaN        NaN

In [27]:
med_groups['N_Benzo'].describe()

count     1014.0
unique     932.0
top          0.0
freq        24.0
Name: N_Benzo, dtype: float64

In [28]:
med_groups['N_Benzo'].median()

0.08663302755175983

### Opiods

In [29]:
for i, r in cohort_med_hour.iterrows():
    if not pd.isnull(r['D_Morphine Sulfate']):
        if not pd.isnull(r['D_Fentanyl']):
            if not pd.isnull(r['D_Fentanyl (Concentrate)']):
                if not pd.isnull(r['D_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'D_Opiod'] = r['D_Morphine Sulfate'] 
                    + (r['D_Fentanyl']/0.01) + (r['D_Fentanyl (Concentrate)']/0.01)
                    + (r['D_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'D_Opiod'] = r['D_Morphine Sulfate'] 
                    + (r['D_Fentanyl']/0.01) + (r['D_Fentanyl (Concentrate)']/0.01)
            else:
                if not pd.isnull(r['D_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'D_Opiod'] = r['D_Morphine Sulfate'] 
                    + (r['D_Fentanyl']/0.01)
                    + (r['D_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'D_Opiod'] = r['D_Morphine Sulfate'] 
                    + (r['D_Fentanyl']/0.01) 
        else:
            if not pd.isnull(r['D_Fentanyl (Concentrate)']):
                if not pd.isnull(r['D_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'D_Opiod'] = r['D_Morphine Sulfate'] 
                    + (r['D_Fentanyl (Concentrate)']/0.01)
                    + (r['D_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'D_Opiod'] = r['D_Morphine Sulfate'] 
                    + (r['D_Fentanyl (Concentrate)']/0.01)
            else:
                if not pd.isnull(r['D_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'D_Opiod'] = r['D_Morphine Sulfate'] 
                    + (r['D_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'D_Opiod'] = r['D_Morphine Sulfate']
    else:
        if not pd.isnull(r['D_Fentanyl']):
            if not pd.isnull(r['D_Fentanyl (Concentrate)']):
                if not pd.isnull(r['D_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'D_Opiod'] = (r['D_Fentanyl']/0.01) 
                    + (r['D_Fentanyl (Concentrate)']/0.01)
                    + (r['D_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'D_Opiod'] =(r['D_Fentanyl']/0.01) 
                    + (r['D_Fentanyl (Concentrate)']/0.01)
            else:
                if not pd.isnull(r['D_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'D_Opiod'] = (r['D_Fentanyl']/0.01)
                    + (r['D_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'D_Opiod'] = (r['D_Fentanyl']/0.01) 
        else:
            if not pd.isnull(r['D_Fentanyl (Concentrate)']):
                if not pd.isnull(r['D_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'D_Opiod'] = (r['D_Fentanyl (Concentrate)']/0.01)
                    + (r['D_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'D_Opiod'] = (r['D_Fentanyl (Concentrate)']/0.01)
            else:
                if not pd.isnull(r['D_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'D_Opiod'] = (r['D_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'D_Opiod'] = np.NAN

In [30]:
med_groups.head()

    icuStay   D_Benzo   N_Benzo   D_Opiod N_Opiod D_Propofol N_Propofol
0  200063.0  0.018391  0.037296  0.344828     NaN        NaN        NaN
1  200069.0       NaN       NaN  0.227273     NaN        NaN        NaN
2  200087.0  0.172506  0.185578  0.923913     NaN        NaN        NaN
3  200282.0  0.268944  0.250288  0.923423     NaN        NaN        NaN
4  200339.0  0.161154  0.358333       NaN     NaN        NaN        NaN

In [32]:
med_groups['D_Opiod'].describe()

count     1967.0
unique    1664.0
top          0.0
freq       104.0
Name: D_Opiod, dtype: float64

In [33]:
for i, r in cohort_med_hour.iterrows():
    if not pd.isnull(r['N_Morphine Sulfate']):
        if not pd.isnull(r['N_Fentanyl']):
            if not pd.isnull(r['N_Fentanyl (Concentrate)']):
                if not pd.isnull(r['N_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'N_Opiod'] = r['N_Morphine Sulfate'] 
                    + (r['N_Fentanyl']/0.01) + (r['N_Fentanyl (Concentrate)']/0.01)
                    + (r['N_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'N_Opiod'] = r['N_Morphine Sulfate'] 
                    + (r['N_Fentanyl']/0.01) + (r['N_Fentanyl (Concentrate)']/0.01)
            else:
                if not pd.isnull(r['N_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'N_Opiod'] = r['N_Morphine Sulfate'] 
                    + (r['N_Fentanyl']/0.01)
                    + (r['N_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'N_Opiod'] = r['N_Morphine Sulfate'] 
                    + (r['N_Fentanyl']/0.01) 
        else:
            if not pd.isnull(r['N_Fentanyl (Concentrate)']):
                if not pd.isnull(r['N_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'N_Opiod'] = r['N_Morphine Sulfate'] 
                    + (r['N_Fentanyl (Concentrate)']/0.01)
                    + (r['N_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'N_Opiod'] = r['N_Morphine Sulfate'] 
                    + (r['N_Fentanyl (Concentrate)']/0.01)
            else:
                if not pd.isnull(r['N_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'N_Opiod'] = r['N_Morphine Sulfate'] 
                    + (r['N_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'N_Opiod'] = r['N_Morphine Sulfate']
    else:
        if not pd.isnull(r['N_Fentanyl']):
            if not pd.isnull(r['N_Fentanyl (Concentrate)']):
                if not pd.isnull(r['N_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'N_Opiod'] = (r['N_Fentanyl']/0.01) 
                    + (r['N_Fentanyl (Concentrate)']/0.01)
                    + (r['N_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'N_Opiod'] =(r['N_Fentanyl']/0.01) 
                    + (r['N_Fentanyl (Concentrate)']/0.01)
            else:
                if not pd.isnull(r['N_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'N_Opiod'] = (r['N_Fentanyl']/0.01)
                    + (r['N_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'N_Opiod'] = (r['N_Fentanyl']/0.01) 
        else:
            if not pd.isnull(r['N_Fentanyl (Concentrate)']):
                if not pd.isnull(r['N_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'N_Opiod'] = (r['N_Fentanyl (Concentrate)']/0.01)
                    + (r['N_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'N_Opiod'] = (r['N_Fentanyl (Concentrate)']/0.01)
            else:
                if not pd.isnull(r['N_Hydromorphone (Dilaudid)']):
                    med_groups.ix[i, 'N_Opiod'] = (r['N_Hydromorphone (Dilaudid)']/0.15)
                else:
                    med_groups.ix[i, 'N_Opiod'] = np.NAN

In [34]:
med_groups.head()

    icuStay   D_Benzo   N_Benzo   D_Opiod   N_Opiod D_Propofol N_Propofol
0  200063.0  0.018391  0.037296  0.344828   0.34965        NaN        NaN
1  200069.0       NaN       NaN  0.227273   0.26087        NaN        NaN
2  200087.0  0.172506  0.185578  0.923913   1.19792        NaN        NaN
3  200282.0  0.268944  0.250288  0.923423  0.527523        NaN        NaN
4  200339.0  0.161154  0.358333       NaN       NaN        NaN        NaN

In [35]:
med_groups['D_Propofol'] = cohort_med_hour['D_Propofol']
med_groups['N_Propofol'] = cohort_med_hour['N_Propofol']

In [36]:
med_groups['D_Dexmedetomidine (Precedex)'] = cohort_med_hour['D_Dexmedetomidine (Precedex)']
med_groups['N_Dexmedetomidine (Precedex)'] = cohort_med_hour['N_Dexmedetomidine (Precedex)']

In [37]:
med_groups.head()

,icuStay,D_Benzo,N_Benzo,D_Opiod,N_Opiod,D_Propofol,N_Propofol,D_Dexmedetomidine (Precedex),N_Dexmedetomidine (Precedex)
0,200063.0,0.018391,0.037296,0.344828,0.34965,46.602329,42.972607,0.005831,0.005498
1,200069.0,NaN,NaN,0.227273,0.26087,2.909091,15.860870,NaN,NaN
2,200087.0,0.172506,0.185578,0.923913,1.19792,NaN,NaN,NaN,NaN
3,200282.0,0.268944,0.250288,0.923423,0.527523,NaN,NaN,NaN,NaN
4,200339.0,0.161154,0.358333,NaN,NaN,40.564085,32.066630,0.001826,0.001089

Adding ICU type

In [38]:
med_groups['last_careunit'] = cohort_med_hour['last_careunit']

In [39]:
unit_cat_ct = med_groups.groupby(['last_careunit']).count()
unit_cat_ct

,icuStay,D_Benzo,N_Benzo,D_Opiod,N_Opiod,D_Propofol,N_Propofol,D_Dexmedetomidine (Precedex),N_Dexmedetomidine (Precedex)
last_careunit,,,,,,,,,
CCU,114,92,89,95,99,64,64,3,2
CSRU,756,127,116,699,707,746,744,140,135
MICU,601,472,470,535,534,361,382,47,46
SICU,387,157,158,322,319,345,354,30,25
TSICU,332,181,181,316,315,296,302,34,26

In [41]:
unit_cat_avg = med_groups.groupby(['last_careunit']).mean()
unit_cat_avg

,icuStay,D_Benzo,D_Propofol,N_Propofol,D_Dexmedetomidine (Precedex),N_Dexmedetomidine (Precedex)
last_careunit,,,,,,
CCU,249042.289474,0.169388,10.834783,9.349106,0.000980,0.001046
CSRU,250805.088624,0.072130,10.705577,8.119932,0.001672,0.001591
MICU,251079.452579,0.239645,15.107686,15.274741,0.002373,0.002037
SICU,251408.266150,0.128776,15.071978,15.345866,0.002165,0.002488
TSICU,251484.801205,0.122372,15.890733,16.833689,0.002559,0.002744